// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { queryField, nullable, list, objectType } from 'nexus';
// nullable is imported since the default is nonNullable in index.ts

import * as gqlTypes from 'nexus-prisma';
import { enumType } from 'nexus';

import { PrismaClient } from '@prisma/client';

const db = new PrismaClient();

export const SportEnum = enumType({
    name: 'Sport',
    members: {
        BADMINTON: 'BADMINTON',
        BASKETBALL: 'BASKETBALL',
        SOCCER: 'SOCCER',
        SWIMMING: 'SWIMMING',
        VOLLEYBALL: 'VOLLEYBALL',
    },
});

// test code doesn't pull from database
// produces Query.hello: String!
export const hello = queryField('hello', {
    type: 'String',
    resolve() {
        return 'Hello World';
    },
});

// produces Query.hi: String!
export const hi = queryField('herro', {
    type: 'String',
    resolve() {
        return 'Hi World';
    },
});
// end of test code

// produces type Person {...}
export const Coachee = objectType({
    name: 'Coachee',
    definition(t) {
        // copy types generated by nexus-prisma
        // nexus Prisma generated Person which was renamed to PersonType
        t.field(gqlTypes.Coachee.id);
        t.field(gqlTypes.Coachee.lastName);
        t.field(gqlTypes.Coachee.firstName);
    },
});
// (OBJECTTYPE DIFFERS FROM QUERY)

// produces Query.people: [Person!]!
export const people = queryField('Coachee', {
    type: list(Coachee),
    resolve() {
        return db.coachee.findMany();
    },
});

export const Coach = objectType({
    name: 'Coach',
    definition(t) {
        t.field(gqlTypes.Coach.id);
        t.field(gqlTypes.Coach.lastName);
        t.field(gqlTypes.Coach.firstName);
        t.field(gqlTypes.Coach.email);
        t.field(gqlTypes.Coach.sport);
        // t.field('sport', { type: SportEnum });
        // t.field('sport', { type: CoachSport });
    },
});

export const coaches = queryField('coaches', {
    type: list(Coach),
    resolve() {
        return db.coach.findMany();
    },
});

// NOTE FILE NOT BEING USED ANYMORE
// JUST KEPT FOR REFERENCE
