import { queryField, list, objectType } from "nexus";

// commented this out myself
// import { Person as PersonType } from "nexus-prisma";

import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

// produces Query.hello: String!
export const hello = queryField("hello", {
  type: "String",
  resolve() {
    return "Hello World";
  },
});

// produces Query.hi: String!
export const hi = queryField("hi", {
  type: "String",
  resolve() {
    return "Hi World";
  },
});

// produces type Person {...}
export const Person = objectType({
  name: "Person",
  definition(t) {
    // copy types generated by nexus-prisma
    t.id("id");
    t.id("familyName");
    t.id("givenName");
    t.id("surveyResults");
  },
});

// produces Query.people: [Person!]!
export const people = queryField("people", {
  type: list(Person),
  resolve() {
    return db.person.findMany();
  },
});
