name: lint-test

on:
  push:
  pull_request:

jobs:
  build:
    name: lint-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }} and Cache (Backend)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies Backend
        run: npm run installDepBackend

      - name: Install Dependencies Frontend
        run: npm run installDepFrontend

      - name: Run ESLint Backend
        run: npm run lintBackend

      - name: Run ESLint
        run: npm run lintFrontend
