name: lint-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: lint-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }} and Cache (Backend)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./backend/package-lock.json

      - name: Install Dependencies Backend
        run: npm ci --prefix ./backend

      - name: Run ESLint Backend
        run: npm run lintBackend

      - name: Use Node.js ${{ matrix.node-version }} and Cache (Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci --prefix ./frontend

      - name: Run ESLint
        run: npm run lintFrontend
